services:
  copaw:
    image: agentscope/copaw:latest
    container_name: copaw
    volumes:
      - /home/docker/copaw:/app/working
    ports:
      - 8088:8088
    restart: always
    network_mode: host
networks: {}
